### ISSUE TITLE
Here are some suggestions for updates.

### ISSUE THREAD

**Issue by CHNWangXi** [cmalf/getgrass-bot-js#1]
It is recommended to modify the following code so that it can fully simulate the latest client.

  if (message.action === "AUTH") {
                    const authResponse = {
                        id: message.id,
                        origin_action: "AUTH",
                        result: {
                            browser_id: deviceId,
                            user_id: userId,
                            user_agent: customHeaders['User-Agent'],
                            timestamp: Math.floor(Date.now() / 1000),
                            device_type: "extension",
                            version: "4.26.2",
                            extension_id: config.extension_id
                        }
                    };
                    logger.debug(authResponse);
                    ws.send(JSON.stringify(authResponse));

It is recommended to change it as follows:

  if (message.action === "AUTH") {
                    const authResponse = {
                        id: message.id,
                        origin_action: "AUTH",
                        result: {
                            browser_id: deviceId,
                            user_id: userId,
                            user_agent: customHeaders['User-Agent'],
                            timestamp: Math.floor(Date.now() / 1000),
                            device_type: "desktop",
                            version: "4.29.0"
                        }
                    };
                    logger.debug(authResponse);
                    ws.send(JSON.stringify(authResponse));

**Comment by cmalf** [comment]
Thanks for the tip! I updated the desktop version a few days ago. Check out the [release](https://github.com/cmalf/getgrass-bot-js/releases/tag/grass-desktop-v0.2) section for the script.
in the main script, just leave it like that, because it is specifically for the extension version of the script.
