### ISSUE TITLE
Brother, it's time to work. Grass has been updated today

### ISSUE THREAD

**Issue by xingxing-dd** [cmalf/getgrass-bot-js#12]
It looks like a new message has arrived that needs to be processed. Is there a solution.
`{"id":"","action":"OPEN_TUNNEL","data":{"url":"https://api.getgrass.io/e65c798e44045cf3241e5bdc52aff12c/JagikGDSwPsY32aF"}}`

**Comment by cmalf** [comment]
- I'm working on it.
the method is almost the same just rotated in several directions!
[getgrass-script-v0.4.1-Freemium-mu](https://github.com/cmalf/getgrass-bot-js/releases/tag/getgrass-script-v0.4.1-Freemium-mu)

**Comment by xingxing-dd** [comment]
> [discussions/9](https://github.com/cmalf/getgrass-bot-js/discussions/9)

Can you give me your password? I have already contacted you on Telegram.Thx
