### ISSUE TITLE
psswd

### ISSUE THREAD

**Issue by stsrebel** [cmalf/getgrass-bot-js#14]
passwrd?👀

**Comment by RqzaX** [comment]
password?

**Comment by rahmap** [comment]
orang indo emang sebodoh ini kah? kan udah ada instruksi nya

**Comment by jomarplay1** [comment]
password is required to avoid patch the script😁

**Comment by lonfger** [comment]
How to get password?

**Comment by Bekloppten** [comment]
just read a lil bit.
dont have it yet, but completed the steps to get it
