### ISSUE TITLE
Auth False - ggb-v0.4.2-Community-Extension-GM-All

### ISSUE THREAD

**Issue by prodesk-1** [cmalf/getgrass-bot-js#19]
ggb-v0.4.2-Community-Extension-GM-All, Not Working

**Comment by cmalf** [comment]
no problem because this is original from grass server.

<hr>

![Screenshot 2024-12-28 at 20 50 08](https://github.com/user-attachments/assets/1e754875-7df6-4ddb-9fea-7607c493f18f)
