### ISSUE TITLE
Error : "authenticated": false (Desktop-Version)

### ISSUE THREAD

**Issue by phuocka** [cmalf/getgrass-bot-js#5]
![error](https://github.com/user-attachments/assets/f3bed62a-6210-46eb-b51d-0bb36204635f)
Error :
"authenticated": false

**Comment by cmalf** [comment]
- Please just use the latest script version, don't use the main script(old script).
- visit [Release](https://github.com/cmalf/getgrass-bot-js/releases) page
- `choose` whether to use version v0.3 or v0.3.1

or visit Discussion [Here](https://github.com/cmalf/getgrass-bot-js/discussions/4)
