### ISSUE TITLE
getgrass add ping type "HTTP_REQUEST"

### ISSUE THREAD

**Issue by cuinima** [cmalf/getgrass-bot-js#7]
The new wss addition is completed.

{
    "id": "g1m08Tpnfbzt-MbCDsc1N",
    "action": "HTTP_REQUEST",
    "data": {
        "url": "http://WsServ-wsser-2YTAKtveCtaD-200e534a774d479a.elb.us-east-1.amazonaws.com/e65c798e44045cf3241e5bdc52aff12c/DOIlvfcTztlJt2rZ",
        "method": "GET",
        "headers": {
            "Accept": "*/*",
            "Host": "wsserv-wsser-2ytaktvectad-200e534a774d479a.elb.us-east-1.amazonaws.com",
            "User-Agent": "wynd.network/3.0.1"
        },
        "authenticated": false
    }
}
{
    "id": "g1m08Tpnfbzt-MbCDsc1N",
    "origin_action": "HTTP_REQUEST",
    "result": {
        "url": "http://wsserv-wsser-2ytaktvectad-200e534a774d479a.elb.us-east-1.amazonaws.com/e65c798e44045cf3241e5bdc52aff12c/DOIlvfcTztlJt2rZ",
        "status": 200,
        "status_text": "OK",
        "headers": {
            "connection": "keep-alive",
            "content-length": "29",
            "content-type": "application/json; charset=utf-8",
            "date": "Thu, 12 Dec 2024 05:58:31 GMT",
            "etag": "W/\"1d-JFi7hFpTL1HGAsMjEGhlaVXTp1I\"",
            "keep-alive": "timeout=5",
            "x-powered-by": "Express"
        },
        "body": "eyJjb2RlIjoiJzZGM0RzMHpDU3l2WnlXWUsnIn0="
    }
}

**Comment by cmalf** [comment]
> The new wss addition is completed.
> 
> { "id": "g1m08Tpnfbzt-MbCDsc1N", "action": "HTTP_REQUEST", "data": { "url": "http://WsServ-wsser-2YTAKtveCtaD-200e534a774d479a.elb.us-east-1.amazonaws.com/e65c798e44045cf3241e5bdc52aff12c/DOIlvfcTztlJt2rZ", "method": "GET", "headers": { "Accept": "_/_", "Host": "wsserv-wsser-2ytaktvectad-200e534a774d479a.elb.us-east-1.amazonaws.com", "User-Agent": "wynd.network/3.0.1" }, "authenticated": false } } { "id": "g1m08Tpnfbzt-MbCDsc1N", "origin_action": "HTTP_REQUEST", "result": { "url": "http://wsserv-wsser-2ytaktvectad-200e534a774d479a.elb.us-east-1.amazonaws.com/e65c798e44045cf3241e5bdc52aff12c/DOIlvfcTztlJt2rZ", "status": 200, "status_text": "OK", "headers": { "connection": "keep-alive", "content-length": "29", "content-type": "application/json; charset=utf-8", "date": "Thu, 12 Dec 2024 05:58:31 GMT", "etag": "W/"1d-JFi7hFpTL1HGAsMjEGhlaVXTp1I"", "keep-alive": "timeout=5", "x-powered-by": "Express" }, "body": "eyJjb2RlIjoiJzZGM0RzMHpDU3l2WnlXWUsnIn0=" } }

Thank you for taking the time to provide those suggestions. I appreciate your effort. However, I've already attempted that method two days ago, and the issue persists on the Grass dashboard.
(still not detected on the Grass dashboard).

- session two days ago that I saved.

![Screenshot 2024-12-12 at 16 52 17](https://github.com/user-attachments/assets/2acd3864-fa8d-4177-8806-05654d27e51f)
![Screenshot 2024-12-12 at 16 52 30](https://github.com/user-attachments/assets/0baa89fc-628f-4712-8ad7-ee8224ac21e7)

**Comment by cmalf** [comment]
but thanks again for bringing this to my attention. I'll take another look at the script to make sure i haven't missed anything important.

**Comment by cuinima** [comment]
I've found that the request "url": "http://wsserv-wsser-2ytaktvectad-200e534a774d479a.elb.us-east-1.amazonaws.com/e65c798e44045cf3241e5bdc52aff12c/DOIlvfcTztlJt2rZ" to return code may be related to the generation of body and etag parameters

**Comment by cmalf** [comment]
> I've found that the request "url": "http://wsserv-wsser-2ytaktvectad-200e534a774d479a.elb.us-east-1.amazonaws.com/e65c798e44045cf3241e5bdc52aff12c/DOIlvfcTztlJt2rZ" to return code may be related to the generation of body and etag parameters

grass developer has updated to version 4.30.0 Desktop.
